---
- block:  
  - name: create timestamp fact
    set_fact:
      current_timestamp: "{{ (ansible_date_time.date + ansible_date_time.time) | regex_replace('[^\\d]','') }}"

  - name: create build folder fact
    set_fact:
      cf_build_folder: "{{ cf_build_folder | default(cf_job_path + '/' + current_timestamp) }}"

  - name: create build folder
    file:
      path: "{{ cf_build_folder }}"
      state: directory
    changed_when: False
  tags:
    - generate