---
- block:
  - name: enable current stack policy
    shell: aws cloudformation set-stack-policy --stack-name '{{ stack.name }}' --stack-policy-body '{{ stack.policy | default(cf_default_stack_policy) | to_json }}'
    changed_when: False

